import os

def print_tree(root_dir, indent="", ignore_dirs=None, ignore_files=None, show_runtime_hint=False):
    """
    Recursively prints a clean project tree structure.

    - Hides autogenerated/build/cache/runtime files
    - Optionally hides runtime folders like data/
    - Produces a clean source-code-only view
    """

    if ignore_dirs is None:
        ignore_dirs = {
            ".git",
            ".venv",
            "__pycache__",
            "node_modules",
            ".next",
            ".turbo",
            ".pytest_cache",
            ".mypy_cache",
            ".idea",
            ".vscode",
            "uploads",
            "chroma",
            "data"   # runtime DB + vector store folder
        }

    if ignore_files is None:
        ignore_files = {
            "rag.db",
            "next-env.d.ts",
            "package-lock.json",
            "folderScanner.py",
            "folderStructure.py"
        }

    try:
        items = sorted(os.listdir(root_dir))
    except (PermissionError, FileNotFoundError):
        return

    for item in items:

        # Skip ignored items
        if item in ignore_dirs or item in ignore_files:
            continue

        path = os.path.join(root_dir, item)

        if os.path.isdir(path):
            print(f"{indent}📁 {item}/")

            print_tree(
                path,
                indent + "   ",
                ignore_dirs,
                ignore_files,
                show_runtime_hint
            )

        else:
            print(f"{indent}📄 {item}")


if __name__ == "__main__":
    project_root = r"C:\Users\ganes_3ck5\DataScience\Gen_AI\Course_GenAI\Gen_AI_In-Depth\resume_projects\chat_with_Doc"
    
    print("\n" + "=" * 60)
    print(f"Project Structure for: {os.path.basename(project_root)}")
    print("=" * 60 + "\n")

    print_tree(project_root)